#!/usr/bin/env python3
"""Cross-platform Tk GUI for SRun campus-network authentication.

Only Python's standard library is used.  A ``config`` file next to this
script stores the account and gateway settings in the same shell-style format
used by the existing scripts in this repository.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import re
import threading
import time
try:
    import tkinter as tk
    from tkinter import messagebox, ttk
except ImportError:  # CLI remains usable on minimal/headless Python installs.
    tk = None
    messagebox = None
    ttk = None
from urllib.parse import parse_qs, urlencode, urlparse
from urllib.request import Request, build_opener, HTTPSHandler, HTTPHandler
import ssl
import shlex
import argparse
import socket
import sys
import platform
import subprocess


ROOT = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(ROOT, "config")
UA = "Mozilla/5.0 (X11; SRun-GUI) AppleWebKit/537.36 Chrome/131 Safari/537.36"
_B64_TRANS = str.maketrans(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    "LVoJPiCN2R8G90yg+hmFHuacZ1OWMnrsSTXkYpUq/3dlbfKwv6xztjI7DeBE45QA",
)


def parse_config(path: str = CONFIG_PATH) -> dict[str, str]:
    """Parse KEY=VALUE lines without executing the config as code."""
    values: dict[str, str] = {}
    if not os.path.isfile(path):
        return values
    for line in open(path, encoding="utf-8"):
        try:
            tokens = shlex.split(line, comments=True, posix=True)
        except ValueError:
            continue
        if not tokens or "=" not in tokens[0]:
            continue
        key, value = tokens[0].split("=", 1)
        if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", key):
            values[key] = value
    return values


def write_config(values: dict[str, str], path: str = CONFIG_PATH) -> None:
    lines = ["# Generated by srun_gui.py; this file contains your password.\n"]
    for key in ("USERNAME", "PASSWORD", "ACID", "SRUN_SCHEME", "SRUN_HOST", "SRUN_THEME", "SRUN_REF_URL", "PROTECT_INTERVAL", "INTERFACE"):
        if key in values and values[key] != "":
            escaped = values[key].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key}="{escaped}"\n')
    with open(path, "w", encoding="utf-8") as fh:
        fh.writelines(lines)
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def _u32(v: int) -> int:
    return v & 0xFFFFFFFF


def _words(data: bytes, include_length: bool) -> list[int]:
    out = []
    for i in range(0, len(data), 4):
        chunk = data[i : i + 4] + b"\0" * (4 - len(data[i : i + 4]))
        out.append(chunk[0] | chunk[1] << 8 | chunk[2] << 16 | chunk[3] << 24)
    if include_length:
        out.append(len(data))
    return out


def xencode(text: str, key: str) -> bytes:
    """SRun's xxtea-compatible xencode implementation (srun_bx1)."""
    data, kdata = text.encode(), key.encode()
    v, k = _words(data, True), _words(kdata, False)
    while len(k) < 4:
        k.append(0)
    if not v:
        return b""
    n, z, q, d = len(v) - 1, 0, 6 + 52 // len(v), 0
    while q:
        q -= 1
        d = _u32(d - 1640531527)
        e = (d >> 2) & 3
        for p in range(n):
            y = v[p + 1]
            mx = _u32(((z >> 5 ^ y << 2) + (y >> 3 ^ z << 4)) ^ ((d ^ y) + (k[(p & 3) ^ e] ^ z)))
            v[p] = _u32(v[p] + mx)
            z = v[p]
        y = v[0]
        mx = _u32(((z >> 5 ^ y << 2) + (y >> 3 ^ z << 4)) ^ ((d ^ y) + (k[(n & 3) ^ e] ^ z)))
        v[n] = _u32(v[n] + mx)
        z = v[n]
    return b"".join(x.to_bytes(4, "little") for x in v)


def encrypted_info(info: str, challenge: str) -> str:
    encoded = base64.b64encode(xencode(info, challenge)).decode().translate(_B64_TRANS)
    return encoded


class SRunClient:
    def __init__(self, config: dict[str, str], log):
        self.c = config
        self.log = log
        self.scheme = config.get("SRUN_SCHEME", "https")
        self.host = config.get("SRUN_HOST", "gw.buaa.edu.cn")
        self.theme = config.get("SRUN_THEME", "buaa")
        self.ref_url = config.get("SRUN_REF_URL", "www.buaa.edu.cn")
        self.domain = config.get("SRUN_DOMAIN", "")
        self.interface = config.get("INTERFACE", "")
        self.base = f"{self.scheme}://{self.host}"
        self.opener = build_opener(HTTPSHandler(context=ssl._create_unverified_context()), HTTPHandler())

    def request(self, url: str, referer: str = "") -> str:
        headers = {"User-Agent": UA, "Accept": "*/*"}
        if referer:
            headers["Referer"] = referer
        req = Request(url, headers=headers)
        with self.opener.open(req, timeout=20) as response:
            return response.read().decode("utf-8", "replace")

    def _acid(self) -> str:
        if self.c.get("ACID"):
            return self.c["ACID"]
        try:
            html = self.request(self.base)
            m = re.search(r"ac_id[^0-9]+([0-9]+)", html)
            if m:
                return m.group(1)
        except Exception:
            pass
        raise RuntimeError("无法获取 ACID，请在 config 中填写 ACID")

    def _challenge(self, acid: str) -> tuple[str, str]:
        page_url = self.c.get("SRUN_LOGIN_PAGE_URL", f"{self.base}/index_1.html?ad_check=1")
        html = self.request(page_url)
        ip = self.c.get("IPADDR") or self.interface_ip()
        if not ip:
            m = re.search(r'id="user_ip"\s+value="([^"]+)"', html)
            ip = m.group(1) if m else "0.0.0.0"
        challenge_url = self.c.get("SRUN_GET_CHALLENGE_URL", f"{self.base}/cgi-bin/get_challenge")
        params = {"callback": "jQuery_srun", "username": self.c["USERNAME"], "ip": ip, "_": str(int(time.time() * 1000))}
        raw = self.request(challenge_url + "?" + urlencode(params), page_url)
        start, end = raw.find("("), raw.rfind(")")
        if start < 0 or end <= start:
            raise RuntimeError("get_challenge 返回格式无法解析")
        obj = json.loads(raw[start + 1 : end])
        challenge, client_ip = obj.get("challenge"), obj.get("client_ip") or ip
        if not challenge:
            raise RuntimeError(obj.get("error_msg") or "获取 Challenge 失败")
        return challenge, client_ip

    def interface_ip(self) -> str:
        if not self.interface:
            return ""
        if platform.system() == "Linux":
            try:
                import fcntl, struct
                sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                raw = fcntl.ioctl(sock.fileno(), 0x8915, struct.pack("256s", self.interface[:15].encode()))
                sock.close()
                return socket.inet_ntoa(raw[20:24])
            except OSError:
                pass
        if platform.system() in ("Darwin", "FreeBSD"):
            try:
                out = subprocess.check_output(["ifconfig", self.interface], text=True, stderr=subprocess.DEVNULL)
                match = re.search(r"inet\s+(\d+\.\d+\.\d+\.\d+)", out)
                if match:
                    return match.group(1)
            except (OSError, subprocess.SubprocessError):
                pass
        return ""

    def online(self) -> tuple[bool, str]:
        url = self.c.get("SRUN_RAD_USER_INFO_URL", f"{self.base}/cgi-bin/rad_user_info")
        try:
            out = self.request(url)
            return "not_online_error" not in out, out
        except Exception as exc:
            return False, str(exc)

    def login(self, logout: bool = False) -> str:
        user, password = self.c.get("USERNAME", ""), self.c.get("PASSWORD", "")
        if not user or (not logout and not password):
            raise RuntimeError("config 缺少 USERNAME 或 PASSWORD")
        acid = self._acid()
        challenge, ip = self._challenge(acid)
        api = self.c.get("SRUN_PORTAL_API_URL", f"{self.base}/cgi-bin/srun_portal")
        common = {"callback": "jQuery_srun", "action": "logout" if logout else "login", "username": user, "ac_id": acid, "ip": ip, "_": str(int(time.time() * 1000))}
        if not logout:
            pwd = hmac.new(challenge.encode(), password.encode(), hashlib.md5).hexdigest()
            info = json.dumps({"username": user, "password": password, "ip": ip, "acid": acid, "enc_ver": "srun_bx1"}, separators=(",", ":"), ensure_ascii=False)
            enc = encrypted_info(info, challenge)
            chk = challenge + user + challenge + pwd + challenge + acid + challenge + ip + challenge + "200" + challenge + "1" + challenge + "{SRBX1}" + enc
            common.update({"password": "{MD5}" + pwd, "chksum": hashlib.sha1(chk.encode()).hexdigest(), "info": "{SRBX1}" + enc, "n": "200", "type": "1", "os": "Python", "name": "Python", "double_stack": self.c.get("BUAA_DOUBLE_STACK", "0")})
        out = self.request(api + "?" + urlencode(common), f"{self.base}/srun_portal_pc?ac_id={acid}&theme={self.theme}")
        self.log(out)
        try:
            i, j = out.find("("), out.rfind(")")
            obj = json.loads(out[i + 1 : j]) if i >= 0 and j > i else {}
            msg = obj.get("error_msg") or obj.get("res") or out
        except Exception:
            msg = out
        return msg


def interface_names() -> list[str]:
    try:
        names = [name for _, name in socket.if_nameindex()]
        if names:
            return ["（系统默认）"] + names
    except OSError:
        pass
    return ["（系统默认）"]


class App:
    def __init__(self, root: tk.Tk):
        self.root, self.worker = root, None
        root.title("SRun 校园网登录")
        root.minsize(500, 360)
        self.vars = {k: tk.StringVar() for k in ("url", "username", "password", "interval", "interface")}
        self.vars["interface"].set("（系统默认）")
        self.protecting = False
        self.status = tk.StringVar(value="就绪")
        self._build()
        self.load_or_setup()

    def _build(self):
        frame = ttk.Frame(self.root, padding=16); frame.pack(fill="both", expand=True)
        fields = [("登录成功页 URL", "url", False), ("学号 / 用户名", "username", False), ("密码", "password", True), ("保活间隔（秒）", "interval", False)]
        for row, (label, key, secret) in enumerate(fields):
            ttk.Label(frame, text=label).grid(row=row, column=0, sticky="w", pady=6)
            ttk.Entry(frame, textvariable=self.vars[key], show="•" if secret else "").grid(row=row, column=1, sticky="ew", pady=6)
        ttk.Label(frame, text="指定网卡").grid(row=4, column=0, sticky="w", pady=6)
        ttk.Combobox(frame, textvariable=self.vars["interface"], values=interface_names(), state="readonly").grid(row=4, column=1, sticky="ew", pady=6)
        frame.columnconfigure(1, weight=1)
        buttons = ttk.Frame(frame); buttons.grid(row=5, column=0, columnspan=2, pady=12)
        ttk.Button(buttons, text="登录", command=lambda: self.run(False)).pack(side="left", padx=4)
        ttk.Button(buttons, text="注销", command=lambda: self.run(True)).pack(side="left", padx=4)
        ttk.Button(buttons, text="保存配置", command=self.save).pack(side="left", padx=4)
        ttk.Button(buttons, text="后台保活", command=self.toggle_protect).pack(side="left", padx=4)
        ttk.Label(frame, textvariable=self.status, foreground="#555").grid(row=6, column=0, columnspan=2, sticky="w")
        self.output = tk.Text(frame, height=9, state="disabled", wrap="word"); self.output.grid(row=7, column=0, columnspan=2, sticky="nsew", pady=(8, 0)); frame.rowconfigure(7, weight=1)

    def append(self, text: str):
        self.root.after(0, lambda: (self.output.configure(state="normal"), self.output.insert("end", text + "\n"), self.output.see("end"), self.output.configure(state="disabled")))

    def load_or_setup(self):
        c = parse_config()
        if c.get("USERNAME"):
            self.vars["username"].set(c.get("USERNAME", "")); self.vars["password"].set(c.get("PASSWORD", "")); self.vars["interval"].set(c.get("PROTECT_INTERVAL", "3600")); self.vars["interface"].set(c.get("INTERFACE", "（系统默认）"))
            scheme, host = c.get("SRUN_SCHEME", "https"), c.get("SRUN_HOST", "gw.buaa.edu.cn"); acid = c.get("ACID", "")
            self.vars["url"].set(f"{scheme}://{host}/srun_portal_success?ac_id={acid}" if acid else f"{scheme}://{host}/srun_portal_success")
        else:
            self.status.set("首次使用：填写登录成功页 URL、账号和密码后点击保存配置")

    def save(self):
        parsed = urlparse(self.vars["url"].get().strip())
        if parsed.scheme not in ("http", "https") or not parsed.hostname:
            messagebox.showerror("URL 错误", "请输入完整的 http(s) 登录成功页 URL")
            return
        q = parse_qs(parsed.query); acid = q.get("ac_id", [""])[0]
        if not self.vars["username"].get() or not self.vars["password"].get():
            messagebox.showerror("信息不完整", "请填写用户名和密码"); return
        values = {"USERNAME": self.vars["username"].get(), "PASSWORD": self.vars["password"].get(), "ACID": acid, "SRUN_SCHEME": parsed.scheme, "SRUN_HOST": parsed.netloc, "SRUN_THEME": "pro", "SRUN_REF_URL": parsed.hostname, "PROTECT_INTERVAL": self.vars["interval"].get() or "3600"}
        iface = self.vars["interface"].get()
        if iface and not iface.startswith("（"):
            values["INTERFACE"] = iface
        write_config(values); self.status.set(f"配置已保存：{CONFIG_PATH}"); self.append("配置已保存（密码仅写入本机 config 文件）")

    def toggle_protect(self):
        if self.protecting:
            self.protecting = False; self.status.set("后台保活已停止"); return
        if not os.path.exists(CONFIG_PATH): self.save()
        c = parse_config()
        if not c.get("USERNAME"): return
        self.protecting = True; self.status.set("后台保活运行中")
        threading.Thread(target=self._protect, args=(c,), daemon=True).start()

    def _protect(self, c):
        try: interval = max(60, int(c.get("PROTECT_INTERVAL", "3600")))
        except ValueError: interval = 3600
        client = SRunClient(c, self.append)
        while self.protecting:
            online, _ = client.online()
            if not online:
                self.append("检测到未联网，尝试自动登录…")
                try: self.append(client.login(False))
                except Exception as exc: self.append("自动登录失败：" + str(exc))
            else:
                self.append("网络认证正常")
            for _ in range(interval):
                if not self.protecting: break
                time.sleep(1)

    def run(self, logout: bool):
        if self.worker and self.worker.is_alive(): return
        if not os.path.exists(CONFIG_PATH): self.save()
        c = parse_config()
        if not c.get("USERNAME"): return
        self.status.set("正在请求认证服务器…"); self.worker = threading.Thread(target=self._run, args=(c, logout), daemon=True); self.worker.start()

    def _run(self, c, logout):
        try:
            result = SRunClient(c, self.append).login(logout); self.root.after(0, lambda: self.status.set("请求完成")); self.append(result)
        except Exception as exc:
            self.root.after(0, lambda: self.status.set("请求失败")); self.append("错误：" + str(exc))


def cli_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="SRun 校园网登录（GUI/CLI）")
    parser.add_argument("command", nargs="?", choices=("login", "logout", "try", "protect"), help="省略时打开 GUI")
    parser.add_argument("--config", default=CONFIG_PATH, help="配置文件路径")
    parser.add_argument("--acid", "-a", help="临时指定 ac_id")
    parser.add_argument("--interface", help="临时指定网卡名称")
    args = parser.parse_args(argv)
    if not args.command:
        if tk is None:
            print("当前 Python 未安装 tkinter，无法启动 GUI；请使用 CLI 或安装 tkinter。", file=sys.stderr)
            return 2
        root = tk.Tk(); App(root); root.mainloop(); return 0
    config = parse_config(args.config)
    if args.acid: config["ACID"] = args.acid
    if args.interface: config["INTERFACE"] = args.interface
    if not config.get("USERNAME"):
        print("缺少 config 或 USERNAME，请先运行 GUI 保存配置。", file=sys.stderr); return 2
    client = SRunClient(config, print)
    if args.command == "login":
        print(client.login(False)); return 0
    if args.command == "logout":
        print(client.login(True)); return 0
    if args.command == "try":
        online, detail = client.online(); print("online" if online else "offline")
        if not online: print(client.login(False))
        return 0
    try: interval = max(60, int(config.get("PROTECT_INTERVAL", "3600")))
    except ValueError: interval = 3600
    print(f"protect 启动，间隔 {interval}s。Ctrl+C 结束。")
    try:
        while True:
            online, _ = client.online()
            if not online:
                try: print(client.login(False))
                except Exception as exc: print("登录失败：", exc, file=sys.stderr)
            time.sleep(interval)
    except KeyboardInterrupt:
        return 0


if __name__ == "__main__":
    raise SystemExit(cli_main(sys.argv[1:]))
